from otree.api import Currency as c, currency_range, SubmissionMustFail as SMF
from . import pages
from ._builtin import Bot
from .models import Constants


class PlayerBot(Bot):
    def play_round(self):
        yield (pages.Introduction)
        yield SMF(
            pages.PersonalityTest,
            dict(
                q_1=15,
                q_2=0,
                q_3=0,
                q_4=0,
                q_5=0,
                q_6=0,
                q_7=0,
                q_8=0,
                q_9=0,
                q_10=0,
                q_11=0,
                q_12=0,
                q_13=0,
                q_14=0,
                q_15=0,
                q_16=0,
                q_17=0,
                q_18=0,
                q_19=0,
                q_20=0,
                q_21=0,
                q_22=0,
                q_23=0,
                q_24=0,
                q_25=0,
                q_26=0,
                q_27=0,
                q_28=0,
            ),
        )
        yield SMF(
            pages.PersonalityTest,
            dict(
                q_1=-1,
                q_2=0,
                q_3=0,
                q_4=0,
                q_5=0,
                q_6=0,
                q_7=0,
                q_8=0,
                q_9=0,
                q_10=0,
                q_11=0,
                q_12=0,
                q_13=0,
                q_14=0,
                q_15=0,
                q_16=0,
                q_17=0,
                q_18=0,
                q_19=0,
                q_20=0,
                q_21=0,
                q_22=0,
                q_23=0,
                q_24=0,
                q_25=0,
                q_26=0,
                q_27=0,
                q_28=0,
            ),
        )
        yield (
            pages.PersonalityTest,
            dict(
                q_1=0,
                q_2=0,
                q_3=0,
                q_4=0,
                q_5=0,
                q_6=0,
                q_7=0,
                q_8=0,
                q_9=0,
                q_10=0,
                q_11=0,
                q_12=0,
                q_13=0,
                q_14=0,
                q_15=0,
                q_16=0,
                q_17=0,
                q_18=0,
                q_19=0,
                q_20=0,
                q_21=0,
                q_22=0,
                q_23=0,
                q_24=0,
                q_25=0,
                q_26=0,
                q_27=0,
                q_28=0,
            ),
        )
